// 豆瓣 Top 250 - 按出品国分类
// 海报路径对应 /posters/ 文件夹内的本地文件，文件名与仓库完全一致
// 每部电影只出现一次，无重复

const m = (zh, en, file) => ({ zh, en, poster: '/posters/' + encodeURIComponent(file) + '.jpg' });

const MOVIES = {

  // ===== 华语电影（中国大陆 · 香港 · 台湾）=====
  chinese: [
    m('霸王别姬',           'Farewell My Concubine',              '霸王别姬'),
    m('活着',               'To Live',                            '活着'),
    m('让子弹飞',           'Let the Bullets Fly',                '让子弹飞'),
    m('鬼子来了',           'Devils on the Doorstep',             '鬼子来了'),
    m('我不是药神',         'Dying to Survive',                   '我不是药神'),
    m('无间道',             'Infernal Affairs',                   '无间道'),
    m('花样年华',           'In the Mood for Love',               '花样年华'),
    m('重庆森林',           'Chungking Express',                  '重庆森林'),
    m('东邪西毒',           'Ashes of Time',                      '东邪西毒'),
    m('春光乍泄',           'Happy Together',                     '春光乍泄'),
    m('功夫',               'Kung Fu Hustle',                     '功夫'),
    m('大话西游之大圣娶亲', 'A Chinese Odyssey Part Two',         '大话西游之大圣娶亲'),
    m('大话西游之月光宝盒', 'A Chinese Odyssey Part One',         '大话西游之月光宝盒'),
    m('一一',               'Yi Yi',                              '一一'),
    m('阳光灿烂的日子',     'In the Heat of the Sun',             '阳光灿烂的日子'),
    m('饮食男女',           'Eat Drink Man Woman',                '饮食男女'),
    m('色，戒',             'Lust, Caution',                      '色，戒'),
    m('喜宴',               'The Wedding Banquet',                '喜宴'),
    m('新龙门客栈',         'New Dragon Gate Inn',                '新龙门客栈'),
    m('甜蜜蜜',             'Comrades: Almost a Love Story',      '甜蜜蜜'),
    m('英雄本色',           'A Better Tomorrow',                  '英雄本色'),
    m('射雕英雄传之东成西就','The Eagle Shooting Heroes',         '射雕英雄传之东成西就'),
    m('唐伯虎点秋香',       'Flirting Scholar',                   '唐伯虎点秋香'),
    m('神偷奶爸',           'Despicable Me',                      '神偷奶爸'),
    m('疯狂的石头',         'Crazy Stone',                        '疯狂的石头'),
    m('驴得水',             'Donkey Gets Water',                  '驴得水'),
    m('四个春天',           'Four Springs',                       '四个春天'),
    m('二十二',             'Twenty Two',                         '二十二'),
    m('九品芝麻官',         'Hail the Judge',                     '九品芝麻官'),
    m('青蛇',               'Green Snake',                        '青蛇'),
  ],

  // ===== 欧美电影（美国·英国·法国·意大利·德国·西班牙等）=====
  western: [
    m('肖申克的救赎',       'The Shawshank Redemption',           '肖申克的救赎'),
    m('阿甘正传',           'Forrest Gump',                       '阿甘正传'),
    m('这个杀手不太冷',     'Léon: The Professional',             '这个杀手不太冷'),
    m('泰坦尼克号',         'Titanic',                            '泰坦尼克号'),
    m('辛德勒的名单',       "Schindler's List",                   '辛德勒的名单'),
    m('盗梦空间',           'Inception',                          '盗梦空间'),
    m('忠犬八公的故事',     "Hachi: A Dog's Tale",                '忠犬八公的故事'),
    m('美丽人生',           'Life Is Beautiful',                  '美丽人生'),
    m('海上钢琴师',         'The Legend of 1900',                 '海上钢琴师'),
    m('星际穿越',           'Interstellar',                       '星际穿越'),
    m('楚门的世界',         'The Truman Show',                    '楚门的世界'),
    m('教父',               'The Godfather',                      '教父'),
    m('搏击俱乐部',         'Fight Club',                         '搏击俱乐部'),
    m('美国往事',           'Once Upon a Time in America',        '美国往事'),
    m('西西里的美丽传说',   'Malèna',                             '西西里的美丽传说'),
    m('天堂电影院',         'Cinema Paradiso',                    '天堂电影院'),
    m('控方证人',           'Witness for the Prosecution',        '控方证人'),
    m('天使爱美丽',         'Amélie',                             '天使爱美丽'),
    m('勇敢的心',           'Braveheart',                         '勇敢的心'),
    m('钢琴家',             'The Pianist',                        '钢琴家'),
    m('指环王3：王者无敌',  'The Return of the King',             '指环王3：王者无敌'),
    m('指环王1：魔戒再现',  'The Fellowship of the Ring',         '指环王1：魔戒再现'),
    m('指环王2：双塔奇兵',  'The Two Towers',                     '指环王2：双塔奇兵'),
    m('闻香识女人',         'Scent of a Woman',                   '闻香识女人'),
    m('飞屋环游记',         'Up',                                 '飞屋环游记'),
    m('机器人总动员',       'WALL·E',                             '机器人总动员'),
    m('心灵捕手',           'Good Will Hunting',                  '心灵捕手'),
    m('放牛班的春天',       'The Chorus',                         '放牛班的春天'),
    m('触不可及',           'The Intouchables',                   '触不可及'),
    m('绿皮书',             'Green Book',                         '绿皮书'),
    m('寻梦环游记',         'Coco',                               '寻梦环游记'),
    m('怦然心动',           'Flipped',                            '怦然心动'),
    m('蝙蝠侠：黑暗骑士',  'The Dark Knight',                    '蝙蝠侠： 黑暗骑士'),
    m('爱在黎明破晓前',     'Before Sunrise',                     '爱在黎明破晓前'),
    m('爱在日落黄昏时',     'Before Sunset',                      '爱在日落黄昏时'),
    m('爱在午夜降临前',     'Before Midnight',                    '爱在午夜降临前'),
    m('沉默的羔羊',         'The Silence of the Lambs',           '沉默的羔羊'),
    m('黑客帝国',           'The Matrix',                         '黑客帝国'),
    m('禁闭岛',             'Shutter Island',                     '禁闭岛'),
    m('爱乐之城',           'La La Land',                         '爱乐之城'),
    m('布达佩斯大饭店',     'The Grand Budapest Hotel',           '布达佩斯大饭店'),
    m('波西米亚狂想曲',     'Bohemian Rhapsody',                  '波西米亚狂想曲'),
    m('当幸福来敲门',       'The Pursuit of Happyness',           '当幸福来敲门'),
    m('本杰明·巴顿奇事',   'The Curious Case of Benjamin Button','本杰明·巴顿奇事'),
    m('2001太空漫游',       '2001: A Space Odyssey',              '2001太空漫游'),
    m('无耻混蛋',           'Inglourious Basterds',               '无耻混蛋'),
    m('蝴蝶效应',           'The Butterfly Effect',               '蝴蝶效应'),
    m('穿条纹睡衣的男孩',   'The Boy in the Striped Pajamas',     '穿条纹睡衣的男孩'),
    m('两杆大烟枪',         'Lock, Stock and Two Smoking Barrels','两杆大烟枪'),
    m('看不见的客人',       'Contratiempo',                       '看不见的客人'),
    m('低俗小说',           'Pulp Fiction',                       '低俗小说'),
    m('教父 2',             'The Godfather Part II',              '教父 2'),
    m('七宗罪',             'Se7en',                              '七宗罪'),
    m('十二怒汉',           '12 Angry Men',                       '十二怒汉'),
    m('爆裂鼓手',           'Whiplash',                           '爆裂鼓手'),
    m('聚焦',               'Spotlight',                          '聚焦'),
    m('房间',               'Room',                               '房间'),
    m('三块广告牌',         'Three Billboards Outside Ebbing, Missouri', '三块广告牌'),
    m('消失的爱人',         'Gone Girl',                          '消失的爱人'),
    m('记忆碎片',           'Memento',                            '记忆碎片'),
    m('追随',               'Following',                          '追随'),
    m('玛丽和马克思',       'Mary and Max',                       '玛丽和马克思'),
    m('飞越疯人院',         "One Flew Over the Cuckoo's Nest",    '飞越疯人院'),
    m('发条橙',             'A Clockwork Orange',                 '发条橙'),
    m('城市之光',           'City Lights',                        '城市之光'),
    m('摩登时代',           'Modern Times',                       '摩登时代'),
    m('乱世佳人',           'Gone with the Wind',                 '乱世佳人'),
    m('罗马假日',           'Roman Holiday',                      '罗马假日'),
    m('音乐之声',           'The Sound of Music',                 '音乐之声'),
    m('傲慢与偏见',         'Pride & Prejudice',                  '傲慢与偏见'),
    m('死亡诗社',           'Dead Poets Society',                 '死亡诗社'),
    m('断背山',             'Brokeback Mountain',                 '断背山'),
    m('谍影重重',           'The Bourne Identity',                '谍影重重'),
  ],

  // ===== 日韩电影（日本·韩国）=====
  japanese: [
    // 宫崎骏
    m('千与千寻',           'Spirited Away',                      '千与千寻'),
    m('哈尔的移动城堡',     "Howl's Moving Castle",               '哈尔的移动城堡'),
    m('龙猫',               'My Neighbor Totoro',                 '龙猫'),
    m('天空之城',           'Castle in the Sky',                  '天空之城'),
    m('幽灵公主',           'Princess Mononoke',                  '幽灵公主'),
    m('魔女宅急便',         "Kiki's Delivery Service",            '魔女宅急便'),
    m('风之谷',             'Nausicaä of the Valley of the Wind', '风之谷'),
    m('侧耳倾听',           'Whisper of the Heart',               '侧耳倾听'),
    m('借东西的小人阿莉埃蒂','The Secret World of Arrietty',      '借东西的小人阿莉埃蒂'),
    // 日本其他
    m('菊次郎的夏天',       'Kikujiro',                           '菊次郎的夏天'),
    m('穿越时空的少女',     'The Girl Who Leapt Through Time',    '穿越时空的少女'),
    m('萤火之森',           'Hotarubi no Mori e',                 '萤火之森'),
    m('萤火虫之墓',         'Grave of the Fireflies',             '萤火虫之墓'),
    m('被嫌弃的松子的一生', 'Memories of Matsuko',                '被嫌弃的松子的一生'),
    m('入殓师',             'Departures',                         '入殓师'),
    m('告白',               'Confessions',                        '告白'),
    m('情书',               'Love Letter',                        '情书'),
    m('步履不停',           'Still Walking',                      '步履不停'),
    m('海街日记',           'Our Little Sister',                  '海街日记'),
    m('小偷家族',           'Shoplifters',                        '小偷家族'),
    m('无人知晓',           'Nobody Knows',                       '无人知晓'),
    m('你的名字。',         'Your Name.',                         '你的名字。'),
    m('东京物语',           'Tokyo Story',                        '东京物语'),
    m('七武士',             'Seven Samurai',                      '七武士'),
    m('罗生门',             'Rashomon',                           '罗生门'),
    // 韩国
    m('寄生虫',             'Parasite',                           '寄生虫'),
    m('杀人回忆',           'Memories of Murder',                 '杀人回忆'),
    m('素媛',               'Hope',                               '素媛'),
    m('熔炉',               'Silenced',                           '熔炉'),
    m('新世界',             'New World',                          '新世界'),
    m('恐怖直播',           'The Terror Live',                    '恐怖直播'),
    m('釜山行',             'Train to Busan',                     '釜山行'),
    m('辩护人',             'The Attorney',                       '辩护人'),
    m('狩猎',               'The Hunt',                           '狩猎'),
    m('完美陌生人',         'Perfect Strangers',                  '完美陌生人'),
    m('未麻的部屋',         'Perfect Blue',                       '未麻的部屋'),
  ],

  // ===== 其他地区（印度·伊朗·泰国·北欧·东欧·拉美等）=====
  other: [
    // 印度
    m('三傻大闹宝莱坞',     '3 Idiots',                           '三傻大闹宝莱坞'),
    m('地球上的星星',       'Taare Zameen Par',                   '地球上的星星'),
    m('贫民窟的百万富翁',   'Slumdog Millionaire',                '贫民窟的百万富翁'),
    m('摔跤吧！爸爸',       'Dangal',                             '摔跤吧！爸爸'),
    m('小萝莉的猴神大叔',   'Bajrangi Bhaijaan',                  '小萝莉的猴神大叔'),
    // 伊朗
    m('一次别离',           'A Separation',                       '一次别离'),
    m('小鞋子',             'Children of Heaven',                 '小鞋子'),
    // 黎巴嫩
    m('何以为家',           'Capernaum',                          '何以为家'),
    // 泰国
    m('初恋这件小事',       'A Little Thing Called Love',         '初恋这件小事'),
    // 德国
    m('窃听风暴',           'The Lives of Others',                '窃听风暴'),
    m('香水',               'Perfume: The Story of a Murderer',   '香水'),
    m('帝国的毁灭',         'Downfall',                           '帝国的毁灭'),
    m('朗读者',             'The Reader',                         '朗读者'),
    // 西班牙
    m('海豚湾',             'The Cove',                           '海豚湾'),
    // 瑞典
    m('一个叫欧维的男人决定去死','A Man Called Ove',             '一个叫欧维的男人决定去死'),
    // 多国/其他
    m('末代皇帝',           'The Last Emperor',                   '末代皇帝'),
    m('上帝之城',           'City of God',                        '上帝之城'),
    m('少年派的奇幻漂流',   'Life of Pi',                         '少年派的奇幻漂流'),
    m('人生果实',           'Fruit of Life',                      '人生果实'),
    m('时空恋旅人',         'About Time',                         '时空恋旅人'),
    m('遗愿清单',           'The Bucket List',                    '遗愿清单'),
    m('海洋',               'Océans',                             '海洋'),
    m('岁月神偷',           'Echoes of the Rainbow',              '岁月神偷'),
    m('再次出发之纽约遇见你','Can a Song Save Your Life?',        '再次出发之纽约遇见你'),
    m('我爱你',             'I Love You',                         '我爱你'),
    m('幸福终点站',         'The Terminal',                       '幸福终点站'),
    m('荒蛮故事',           'Wild Tales',                         '荒蛮故事'),
    m('你看起来好像很好吃', 'Natsume\'s Book of Friends',         '你看起来好像很好吃'),
    m('奇迹男孩',           'Wonder',                             '奇迹男孩'),
    m('阳光姐妹淘',         'Sunny',                              '阳光姐妹淘'),
    m('海蒂和爷爷',         'Heidi',                              '海蒂和爷爷'),
    m('小森林 冬春篇',      'Little Forest: Winter/Spring',       '小森林 冬春篇'),
    m('小森林 夏秋篇',      'Little Forest: Summer/Autumn',       '小森林 夏秋篇'),
    m('可可西里',           'Kekexili: Mountain Patrol',          '可可西里'),
  ],
};
